---
#
# add a swapfile: create a swapfile, add mount, enable swap
#
# vars:
#  swap_size: 1G
#
# swap_file is set to /{{swap_size}}.swap
#

- name: set_fact swap_file
  set_fact:
    swap_file: "/{{swap_size}}.swap"

- name: Create swap space
  command: fallocate -l {{swap_size}} {{swap_file}}
  # the count computation is not working of course, but must be done
  #command: dd if=/dev/zero of={{swap_file}} bs=256M count={{swap_size / 256M}}
  when: ansible_swaptotal_mb < 1

- name: Set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600
    owner: root
    group: root

- name: Make swap
  command: mkswap {{swap_file}}
  when: ansible_swaptotal_mb < 1

- name: write swap entry in fstab
  mount:
    name: none
    src: "{{swap_file}}"
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
    state: present

- name: Turn swap on
  command: swapon -a
  when: ansible_swaptotal_mb < 1

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"

- name: set vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "100"
